### ISSUE TITLE
貌似不行啊

### ISSUE THREAD

**Issue by maysrp** [qfdk/BtOnline#1]

**Comment by qfdk** [comment]
@maysrp 首先感谢对项目的关注 ：）很抱歉今天才回复您的issue

项目测试是可以运行的，正在做其他的修改，可能影响您的使用。
重大更新会在hostloc进行说明。

本项目一直在进行

**Comment by maysrp** [comment]
咦 ~~来个测试地址看看？？
想搞在SSBC的搜索结果上 搞一个在线播放

**Comment by qfdk** [comment]
@maysrp 一年多的ticket了. 不好意思现在再回复.

本项目一直在进行.
